Ruslan
MaxChabanov/student-app pull request #4
Opened 2021-09-15 14:37 UTC by WoodsOfTroy

ЫЫыыыыыыыыыыыыыыыыыыыыы

2021-09-15 14:58 UTC, MaxChabanov requested changes
Убрать зипы в assets/images

2021-09-15 14:58 UTC, MaxChabanov commented on angular.json
> +  },
Убрать, вызывает конфликт

2021-09-15 14:58 UTC, MaxChabanov commented on src/app/index.html
> +<!doctype html>
Удалить, копия index.html в src

2021-09-15 14:58 UTC, MaxChabanov commented on src/app/main.ts
> +import { enableProdMode } from '@angular/core';
убрать все файли в app с test.ts по fav.ico

2021-09-18 08:11 UTC, AlexeySolovey reviewed
Удалены лишние файлы  .browserlistrc, .editorconfig, .gitignore

2021-09-18 09:11 UTC, AlexeySolovey approved these changes

2021-09-18 10:37 UTC, MaxChabanov approved these changes
Все ок

2021-09-18 10:37 UTC, merged